language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
sbt_args:  -J-Xms1600m -J-Xmx1600m -J-XX:MaxMetaspaceSize=1024m
services:
    - mongodb

notifications:
  slack: reallyio:5GS2VfddFeJUWmxJ2tHW9ajS
